### PR TITLE
Enable magic comments in (X)HTML

### PR DESCRIPTION
**Pull request by JonasWischeropp**
This PR makes it possible to use magic comments in HTML files (#31).

### CODE REVIEW

**Comment by JonasWischeropp** [comment]
Converted to draft, because I decided to make some changes.

**Comment by JonasWischeropp** [comment]
I have implemented a proper `HtmlFragmentizer`.
Before the complete document was checked, resulting in a lot of false positives. These were especially prominent in non-English languages, where strings like `body` or `id` inside tags (`<body>`, `<p id="...">`) were checked.
Now, only the text in between tags is checked (`<Not checked>Checked</Not checked>`) and magic comments are supported.

**Comment by spitzerd** [comment]
Thank you for your contribution of a new feature and the corresponding tests 👍 I will merge your pull request and add you and your feature in changelog.xml
I am looking forward to see you again as contributor for LTeX+

**Comment by JonasWischeropp** [comment]
Thank you. I see you have also already adjusted the documentation👍.

**Pull request merged**
